In [1]:
#import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# import dataset
comp = pd.read_csv("D:/DATA SCIENCE/1. Data Scientist/Assignment/14.Random Forests/Company_Data.csv")

In [3]:
comp.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [7]:
comp.shape

(400, 11)

In [4]:
comp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB


In [5]:
comp.describe()

Sales   CompPrice      Income  Advertising  Population  \
count  400.000000  400.000000  400.000000   400.000000  400.000000   
mean     7.496325  124.975000   68.657500     6.635000  264.840000   
std      2.824115   15.334512   27.986037     6.650364  147.376436   
min      0.000000   77.000000   21.000000     0.000000   10.000000   
25%      5.390000  115.000000   42.750000     0.000000  139.000000   
50%      7.490000  125.000000   69.000000     5.000000  272.000000   
75%      9.320000  135.000000   91.000000    12.000000  398.500000   
max     16.270000  175.000000  120.000000    29.000000  509.000000   

            Price         Age   Education  
count  400.000000  400.000000  400.000000  
mean   115.795000   53.322500   13.900000  
std     23.676664   16.200297    2.620528  
min     24.000000   25.000000   10.000000  
25%    100.000000   39.750000   12.000000  
50%    117.000000   54.500000   14.000000  
75%    131.000000   66.000000   16.000000  
max    191.000000   80.000000   18.000000

In [8]:
# Look for unique value 
comp["Sales"].unique()

array([ 9.5 , 11.22, 10.06,  7.4 ,  4.15, 10.81,  6.63, 11.85,  6.54,
        4.69,  9.01, 11.96,  3.98, 10.96, 11.17,  8.71,  7.58, 12.29,
       13.91,  8.73,  6.41, 12.13,  5.08,  5.87, 10.14, 14.9 ,  8.33,
        5.27,  2.99,  7.81, 13.55,  8.25,  6.2 ,  8.77,  2.67, 11.07,
        8.89,  4.95,  6.59,  3.24,  2.07,  7.96, 10.43,  4.12,  4.16,
        4.56, 12.44,  4.38,  3.91, 10.61,  1.42,  4.42,  7.91,  6.92,
        4.9 ,  6.85, 11.91,  0.91,  5.42,  5.21,  8.32,  7.32,  1.82,
        8.47,  7.8 ,  8.85, 13.39,  7.99,  9.46,  6.5 ,  5.52, 12.61,
        8.55, 10.64,  7.7 ,  4.43,  9.14,  8.01,  7.52, 11.62,  2.23,
        8.7 , 11.7 ,  6.56,  7.95,  5.33,  4.81,  4.53,  8.86,  8.39,
        5.58,  9.48,  7.45, 12.49,  4.88,  4.11,  5.3 ,  5.07,  4.62,
        5.55,  0.16,  3.47,  8.98,  9.  ,  6.62,  6.67,  6.01,  9.31,
        8.54,  8.8 ,  7.57,  7.37,  6.87, 11.67,  6.88,  8.19,  8.87,
        9.34, 11.27,  6.52,  4.96,  4.47,  8.41,  9.54,  7.62,  3.67,
        6.44,  5.17,

In [10]:
# checking how many times each number is repeating
comp["Sales"].value_counts()

7.80     4
6.67     3
8.77     3
9.32     3
5.87     3
        ..
8.89     1
13.39    1
9.14     1
5.07     1
9.50     1
Name: Sales, Length: 336, dtype: int64

In [13]:
# from comp.describe() we get to know sales.mean=7.496325
comp["sales"]="<=7.49"
comp.loc[comp["Sales"]>=7.49,"sales"]=">=7.49"

In [14]:
comp.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US   sales  
0         17   Yes  Yes  >=7.49  
1         10   Yes  Yes  >=7.49  
2         12   Yes  Yes  >=7.49  
3         14   Yes  Yes  <=7.49  
4         13   Yes   No  <=7.49

In [15]:
##Drop variable =  "Sales"
comp.drop(["Sales"],axis=1,inplace=True)

In [17]:
# Encoding
# model.fit doesnt convert string data to float
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for column_names in comp.columns:
    if comp[column_names].dtype == object:
        comp[column_names]= le.fit_transform(comp[column_names])
    else:
        pass

In [20]:
comp.head()

CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0        138      73           11         276    120          0   42   
1        111      48           16         260     83          1   65   
2        113      35           10         269     80          2   59   
3        117     100            4         466     97          2   55   
4        141      64            3         340    128          0   38   

   Education  Urban  US  sales  
0         17      1   1      1  
1         10      1   1      1  
2         12      1   1      1  
3         14      1   1      0  
4         13      1   0      0

In [26]:
#Splitting the data into x_feature() and y_labels
x_featues = comp.iloc[:,0:10]
y_labels = comp.iloc[:,10]

In [27]:
# Collecting the column names
colnames = list(comp.columns)
predictors = colnames[0:10]
target = colnames[10]

In [29]:
# here Splitting the data into train and test by using stratify sampling
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_featues,y_labels,test_size = 0.3,stratify = y_labels) 

In [30]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((280, 10), (280,), (120, 10), (120,))

In [31]:
##Looking into the class variable split
y_train.value_counts()

y_test.value_counts()

1    60
0    60
Name: sales, dtype: int64

In [60]:
# model building
from sklearn.ensemble import RandomForestClassifier as RF
model =RF(n_jobs=4,n_estimators = 150, oob_score =True,criterion ='entropy') 
model.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=150, n_jobs=4,
                       oob_score=True)

In [61]:
model.classes_

array([0, 1])

In [62]:
model.n_features_

10

In [63]:
model.n_outputs_

1

In [64]:
model.n_classes_

2

In [65]:
model.oob_score_

0.7928571428571428

In [66]:
#Predicting on training data
pred_train = model.predict(x_train)

In [67]:
#Accuracy on training data
from sklearn.metrics import accuracy_score
accuracy_train = accuracy_score(y_train,pred_train)

In [68]:
np.mean(pred_train == y_train)

1.0

In [69]:
# creating Confusion matrix
from sklearn.metrics import confusion_matrix
con_train = confusion_matrix(y_train,pred_train)

In [70]:
#Prediction on test data
pred_test = model.predict(x_test)

In [71]:
##Accuracy on test data
accuracy_test = accuracy_score(y_test,pred_test)

In [72]:
np.mean(y_test==pred_test)

0.7916666666666666

In [73]:
##Confusion matrix
con_test = confusion_matrix(y_test,pred_test)

In [74]:
con_test

array([[49, 11],
       [14, 46]], dtype=int64)

In [75]:
# plot a Decision tree present in Random forest
import pydotplus
from io import StringIO
from sklearn.tree import export_graphviz

In [76]:
tree1 = model.estimators_[20]

In [77]:
dot_data = StringIO()
export_graphviz(tree1,out_file = dot_data, feature_names =predictors, class_names = target, filled =True,rounded=True,impurity =False,proportion=False,precision =2)

In [78]:
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())

In [79]:
# for selected decision tree Creating pdf and png file 
graph.write_pdf('comprf.pdf')
graph.write_png('comprf.png')

True