In [1]:
import pandas as pd
import scipy 
import numpy as np
from scipy import stats

In [2]:
data=pd.read_csv('D:/DATA SCIENCE/1. Data Scientist/Assignment/3. hypothesis testing/Costomer+OrderForm.csv')

In [3]:
data.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [4]:
obj_df = data.select_dtypes(include=['object']).copy()
obj_df.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [5]:
obj_df[obj_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Phillippines, Indonesia, Malta, India]
Index: []

In [6]:
obj_df["Phillippines"].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [7]:
obj_df["Indonesia"].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [8]:
obj_df["Malta"].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [9]:
obj_df["India"].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [11]:
cleanup_nums = {"Phillippines":{"Error Free": 1, "Defective": 0},
                "Indonesia":{"Error Free": 1, "Defective": 0},
                "Malta":{"Error Free": 1, "Defective": 0},
                "India": {"Error Free": 1, "Defective": 0}}

In [12]:
obj_df = obj_df.replace(cleanup_nums)
obj_df.head()

Phillippines  Indonesia  Malta  India
0             1          1      0      1
1             1          1      1      0
2             1          0      0      1
3             1          1      1      1
4             1          1      0      1

In [13]:
d1=obj_df["Phillippines"]

In [14]:
d2=obj_df["Indonesia"]

In [15]:
d3=obj_df["Malta"]

In [16]:
d4=obj_df["India"]

In [20]:
obj_df["Phillippines"]

0      1
1      1
2      1
3      1
4      1
      ..
295    1
296    1
297    1
298    1
299    1
Name: Phillippines, Length: 300, dtype: int64

In [21]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2


In [22]:
table = [[d1],[d2],[d3],[d4]]
print(table)

[[0      1
1      1
2      1
3      1
4      1
      ..
295    1
296    1
297    1
298    1
299    1
Name: Phillippines, Length: 300, dtype: int64], [0      1
1      1
2      0
3      1
4      1
      ..
295    1
296    1
297    1
298    1
299    0
Name: Indonesia, Length: 300, dtype: int64], [0      0
1      1
2      0
3      1
4      0
      ..
295    1
296    1
297    0
298    1
299    0
Name: Malta, Length: 300, dtype: int64], [0      1
1      0
2      1
3      1
4      1
      ..
295    1
296    1
297    1
298    1
299    1
Name: India, Length: 300, dtype: int64]]


In [23]:
stat, p, dof, expected = chi2_contingency(table)
print('dof=%d' % dof)
print(expected)

dof=897
[[[0.74793008 0.74793008 0.49862006 ... 0.74793008 0.99724011 0.49862006]]

 [[0.73689052 0.73689052 0.49126035 ... 0.73689052 0.9825207  0.49126035]]

 [[0.7424103  0.7424103  0.4949402  ... 0.7424103  0.9898804  0.4949402 ]]

 [[0.77276909 0.77276909 0.51517939 ... 0.77276909 1.03035879 0.51517939]]]


In [24]:
prob = 0.95
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))


probability=0.950, critical=967.787, stat=112.747


In [25]:
alpha = 0.05
print('significance=%.3f, p=%.3f' % (alpha, p))

significance=0.050, p=1.000


In [ ]:
#HO=defective of % of all countries are equal
#H1=not all are equal
so we get
p>alpha,1.000>0.05
as per given codition 
#we fail to reject null hypothesis(H0),defective of % of all countries are equal